project:
  type: book
  output-dir: ../_site/download   # or just "print" if you prefer

book:
  title: "pai721f25"
  chapters:
    - index.qmd                # cover/intro page (required)
    - ../syllabus.qmd
    - ../schedule.qmd
    - ../policies.qmd

format:
  pdf:
    toc: true
    documentclass: article
    top-level-division: section
  docx:
    toc: true