project:
  type: book
  output-dir: ../_site/download   # or just "print" if you prefer

book:
  title: "PAI 721 - Course Packet"
  subtitle: "Fall 2025"
  author: 
    - name: "Jack Reilly"
    - affiliation: "Maxwell School, Syracuse University"
  chapters:
    - index.qmd                # cover/intro page (required)
    - ../syllabus.qmd
    - ../schedule.qmd
    - ../policies.qmd

format:
  pdf:
    toc: true
    documentclass: article
    top-level-division: section
    output-file: 721coursepack
  docx:
    toc: true
    output-file: 721coursepack